<?php
include("conexion.php");

$CODIGOARTICULO=$_GET["CODIGOARTICULO"];
$SECCION=$_GET["SECCION"];
$NOMBREARTICULO=$_GET["NOMBREARTICULO"];
$PRECIO=$_GET["PRECIO"];
$FECHA=$_GET["FECHA"];
$IMPORTADO=$_GET["IMPORTADO"];
$PAISDEORIGEN=$_GET["PAISDEORIGEN"];

$base->query("UPDATE productos SET CODIGOARTICULO='$CODIGOARTICULO', SECCION='$SECCION', NOMBREARTICULO='$NOMBREARTICULO', PRECIO='$PRECIO', FECHA='$FECHA', IMPORTADO='$IMPORTADO', PAISDEORIGEN='$PAISDEORIGEN'  WHERE CODIGOARTICULO='$CODIGOARTICULO'");
header("Location:indexInicial.php");
?>